### PR TITLE
Updated with more versions of nodejs

### LINKED ISSUE #24: Add more Node versions to Travis CI build
The build is only run against Node 6.0 and 6.1, ideally the build should run against all minor versions starting from Node 6 up to the current (stable) version.

### PR DESCRIPTION
**Pull request by adnrs96**
In this PR i have added more nodejs versions in travis.yml file so as to run builds with.
This PR resolves #24

### CODE REVIEW

**Review by ovidiubute — CHANGES_REQUESTED** [review]
Looking good, however I think you should leave "6" in because that means the latest stable release. This way we don't need to update it constantly. 

Please also merge the `master` branch in your PR.

Looking good otherwise!

**Review by ovidiubute — APPROVED** [review]

**Comment by adnrs96** [comment]
@ovidiubute Thank you for reviewing my PR.
I just wanted to ask a silly question, is it considered a bad practice when there are unnecessary number of commits  made to project. Like i just added 3 commits for just a small change.

**Comment by ovidiubute** [comment]
@adnrs96 you're welcome. It doesn't really matter how many commits you make in your PR because when I merged it I squashed all of the commits into a single one. If you check the git log of the project now you'll see what I mean 😄

**Comment by adnrs96** [comment]
@ovidiubute Ohk now i understand. So this way commit log remains clean irrespective of number of useless commits made.Thanks for helping me understand it.

**Pull request merged**
